import json
import logging
import time
import threading
from pathlib import Path

from openai import OpenAI, APIConnectionError, APITimeoutError, APIStatusError

from config import LM_STUDIO_URL, LM_STUDIO_MODEL, SYSTEM_PROMPT, MAX_HISTORY, HISTORY_FILE
from tools import TOOLS, execute_tool

logger = logging.getLogger(__name__)

_client = None
_client_lock = threading.Lock()
_history = []
_history_lock = threading.Lock()


class CircuitBreaker:
    def __init__(self, failure_threshold=5, recovery_timeout=60):
        self.failure_threshold = failure_threshold
        self.recovery_timeout = recovery_timeout
        self._failures = 0
        self._last_failure = 0.0
        self._lock = threading.Lock()

    def record_success(self):
        with self._lock:
            self._failures = 0

    def record_failure(self):
        with self._lock:
            self._failures += 1
            self._last_failure = time.monotonic()

    def is_open(self) -> bool:
        with self._lock:
            if self._failures < self.failure_threshold:
                return False
            if (time.monotonic() - self._last_failure) >= self.recovery_timeout:
                self._failures = 0
                return False
            return True


_circuit = CircuitBreaker()


def _get_client():
    global _client
    with _client_lock:
        if _client is None:
            _client = OpenAI(base_url=LM_STUDIO_URL, api_key="lm-studio")
        return _client


def _get_history_path() -> str:
    """Получить путь к файлу истории для текущего профиля."""
    import profiles as prof
    current = prof.get_current()
    if current:
        return prof.get_history_path()
    return HISTORY_FILE


def load_history():
    global _history
    history_path = Path(_get_history_path())
    if history_path.exists():
        try:
            with open(history_path, "r", encoding="utf-8") as f:
                _history = json.load(f)
            logger.info("Загружена история (%s): %d сообщений.", history_path.name, len(_history))
        except (json.JSONDecodeError, IOError) as e:
            logger.warning("Ошибка загрузки истории: %s. Начинаем с пустой.", e)
            _history = []
    else:
        _history = []


def save_history():
    try:
        history_path = _get_history_path()
        with open(history_path, "w", encoding="utf-8") as f:
            json.dump(_history, f, ensure_ascii=False, indent=2)
    except IOError as e:
        logger.error("Ошибка сохранения истории: %s", e)


def switch_profile_history():
    """Сохранить историю текущего профиля и загрузить историю нового."""
    save_history()
    load_history()


def _build_messages(user_text: str) -> list[dict]:
    import profiles as prof
    current = prof.get_current()
    system_prompt = current.get("system_prompt", SYSTEM_PROMPT) if current else SYSTEM_PROMPT

    with _history_lock:
        _history.append({"role": "user", "content": user_text})
        if len(_history) > MAX_HISTORY:
            _history.pop(0)
        return [{"role": "system", "content": system_prompt}] + list(_history)


def _save_answer(answer: str):
    if not answer or not answer.strip():
        logger.warning("Пустой ответ от LLM, не сохраняем в историю.")
        return
    with _history_lock:
        _history.append({"role": "assistant", "content": answer})
        if len(_history) > MAX_HISTORY:
            _history.pop(0)
    save_history()


def ask(user_text: str) -> str:
    if _circuit.is_open():
        raise ConnectionError("LLM сервис недоступен (circuit breaker открыт). Попробуйте позже.")

    messages = _build_messages(user_text)
    client = _get_client()

    max_retries = 3
    for attempt in range(max_retries):
        try:
            response = client.chat.completions.create(
                model=LM_STUDIO_MODEL or "default",
                messages=messages,
            )
            answer = response.choices[0].message.content
            _circuit.record_success()
            _save_answer(answer)
            return answer
        except (APIConnectionError, APITimeoutError) as e:
            _circuit.record_failure()
            logger.warning("LLM ошибка (попытка %d/%d): %s", attempt + 1, max_retries, e)
            if attempt < max_retries - 1:
                time.sleep(2 ** attempt)
            else:
                raise ConnectionError(f"LLM недоступен после {max_retries} попыток: {e}") from e
        except APIStatusError as e:
            _circuit.record_failure()
            logger.error("LLM статус-ошибка %d: %s", e.status_code, e.message)
            raise


def ask_stream(user_text: str, messages: list[dict] = None):
    """Yield text chunks as they are generated by the LLM."""
    if _circuit.is_open():
        raise ConnectionError("LLM сервис недоступен (circuit breaker открыт). Попробуйте позже.")

    if messages is None:
        messages = _build_messages(user_text)
    client = _get_client()

    max_retries = 3
    for attempt in range(max_retries):
        try:
            stream = client.chat.completions.create(
                model=LM_STUDIO_MODEL or "default",
                messages=messages,
                stream=True,
            )
            full_answer = ""
            for chunk in stream:
                if chunk.choices and chunk.choices[0].delta.content:
                    token = chunk.choices[0].delta.content
                    full_answer += token
                    yield token
            _circuit.record_success()
            _save_answer(full_answer)
            return
        except (APIConnectionError, APITimeoutError) as e:
            _circuit.record_failure()
            logger.warning("LLM stream ошибка (попытка %d/%d): %s", attempt + 1, max_retries, e)
            if attempt < max_retries - 1:
                time.sleep(2 ** attempt)
            else:
                raise ConnectionError(f"LLM недоступен после {max_retries} попыток: {e}") from e
        except APIStatusError as e:
            _circuit.record_failure()
            logger.error("LLM статус-ошибка %d: %s", e.status_code, e.message)
            raise


def _stream_text(client, messages) -> str:
    """Streaming запрос. Yield token'ы, возвращает полный ответ."""
    stream = client.chat.completions.create(
        model=LM_STUDIO_MODEL or "default",
        messages=messages,
        stream=True,
    )
    full_answer = ""
    for chunk in stream:
        if chunk.choices and chunk.choices[0].delta.content:
            token = chunk.choices[0].delta.content
            full_answer += token
            yield token
    return full_answer


def _clean_tool_msg(msg) -> dict:
    """Очищаем сообщение от лишних полей (refusal и т.д.) чтобы LM Studio не ломался."""
    clean = {"role": msg.role}
    if msg.content:
        clean["content"] = msg.content
    if msg.tool_calls:
        clean["tool_calls"] = [
            {
                "id": tc.id,
                "type": "function",
                "function": {"name": tc.function.name, "arguments": tc.function.arguments},
            }
            for tc in msg.tool_calls
        ]
    return clean


def ask_with_tools(user_text: str):
    """Запрос к LLM с поддержкой tool calling. Yield token'ы ответа."""
    if _circuit.is_open():
        raise ConnectionError("LLM сервис недоступен (circuit breaker открыт). Попробуйте позже.")

    messages = _build_messages(user_text)
    client = _get_client()

    max_retries = 3
    for attempt in range(max_retries):
        try:
            response = client.chat.completions.create(
                model=LM_STUDIO_MODEL or "default",
                messages=messages,
                tools=TOOLS,
                tool_choice="auto",
            )

            choice = response.choices[0]
            msg = choice.message

            logger.debug(
                "LLM response: content=%s, tool_calls=%s, finish_reason=%s",
                repr(msg.content[:80]) if msg.content else None,
                len(msg.tool_calls) if msg.tool_calls else 0,
                choice.finish_reason,
            )

            if msg.tool_calls:
                messages.append(_clean_tool_msg(msg))

                for tc in msg.tool_calls:
                    fn_name = tc.function.name
                    try:
                        fn_args = json.loads(tc.function.arguments)
                    except json.JSONDecodeError:
                        fn_args = {}
                    logger.info("Tool call: %s(%s)", fn_name, fn_args)

                    result = execute_tool(fn_name, fn_args)

                    messages.append({
                        "role": "tool",
                        "tool_call_id": tc.id,
                        "content": str(result),
                    })

                _circuit.record_success()

                full_answer = ""
                for token in _stream_text(client, messages):
                    full_answer += token
                    yield token

                if full_answer.strip():
                    _save_answer(full_answer)
                    return

                logger.warning("Tool calling вернул пустой ответ, fallback на ask_stream.")
                yield from ask_stream(user_text, messages=messages)
                return

            elif msg.content:
                _circuit.record_success()
                messages.append({"role": "assistant", "content": msg.content})

                for char in msg.content:
                    yield char

                _save_answer(msg.content)
                return

            else:
                logger.warning("LLM вернул и content=None, и tool_calls=None. Fallback на ask_stream.")
                _circuit.record_success()
                yield from ask_stream(user_text, messages=messages)
                return

        except (APIConnectionError, APITimeoutError) as e:
            _circuit.record_failure()
            logger.warning("LLM tools ошибка (попытка %d/%d): %s", attempt + 1, max_retries, e)
            if attempt < max_retries - 1:
                time.sleep(2 ** attempt)
            else:
                raise ConnectionError(f"LLM недоступен после {max_retries} попыток: {e}") from e
        except APIStatusError as e:
            _circuit.record_failure()
            logger.error("LLM статус-ошибка %d: %s", e.status_code, e.message)
            raise
